### ISSUE TITLE
how to change players

### ISSUE THREAD

**Issue by incandescentman** [lujun9972/podcaster#6]
When I try to change players, e.g. 

```
(setq podcaster-mp3-player "VLC")
```

or 

```
(setq podcaster-mp3-player "33\\ RPM")
```

I get the error: `'VLC' is not supported!!`

**Comment by lujun9972** [comment]
I am sorry, right now,It only support avplay,ffplay or itunes because I don't know how to use vlc to play mp3 without gui

**Comment by lujun9972** [comment]
Hi, would you please update the podcaster and try again?

**Comment by incandescentman** [comment]
Try again to do what? Change the player?
ᐧ

---

Jay Dixit
(646) 355-8001
newyorkwritersintensive.com

**Comment by lujun9972** [comment]
yes
