### ISSUE TITLE
feature request: podcast names in completing-read

### ISSUE THREAD

**Issue by ajjackson** [lujun9972/podcaster#7]
This is a really cool project and I'd like to use it to explore some new podcasts. The problem is that not every podcast has a sensible naming convention for episodes! As a result, to search on a particular podcast we have to manipulate the feeds list before calling podcaster; as we're using completing-read this would be much easier with pattern matching. For example, a list

```
a vague name
other vague name
some mix
...
```

could show as

```
the spooky show - a vague name
cooking 101 - other vague name
awesomeDJ - some mix
...
```

Then with Helm or Ivy we can type "spooky" to narrow down the selection, and with basic completion we can still go `t TAB oth TAB` or similar.
This would involve changing the infrastructure a bit as the lookup currently uses the Title returned by completing-read. There would also need to be some kind of logic to assign names to podcasts, maybe with an alist version of podcaster-feeds-urls.

**Comment by lujun9972** [comment]
Thank your for your advise. 
I have made some change, Please check is that what you want?

**Comment by ajjackson** [comment]
Yes, that's great!
